spring :
  application :
    name : eureka-client1
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2