server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zblog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
